import type { ScanReport } from '../types.js';

/**
 * Writes the .env.example the repository should have shipped with: every
 * discovered value, grouped by ecosystem, annotated with where it is read
 * and what it falls back to.
 */
export function renderEnvExample(report: ScanReport): string {
  const lines: string[] = [
    '# Generated by runready — every value this repository reads at runtime.',
    '# Copy to .env and fill in the blanks.',
  ];

  const groups = new Map<string, typeof report.config>();
  for (const entry of report.config) {
    const group = groups.get(entry.ecosystem) ?? [];
    group.push(entry);
    groups.set(entry.ecosystem, group);
  }

  for (const [ecosystem, entries] of [...groups.entries()].sort()) {
    lines.push('', `# --- ${ecosystem} ---`);
    for (const entry of entries) {
      const source = entry.sources[0];
      if (source) {
        lines.push(`# read at ${source.file}:${source.line}`);
      }
      if (entry.defaultValue !== undefined) {
        lines.push(`# optional — defaults to ${entry.defaultValue || '(empty)'}`);
        lines.push(`# ${entry.name}=`);
      } else {
        lines.push(`${entry.name}=`);
      }
    }
  }

  return `${lines.join('\n')}\n`;
}
